// Generated by CoffeeScript 1.4.0
(function() {
  var MutationObserver, button, commentForm, insertButtons, observer, selectElements,
    _this = this;

  commentForm = document.querySelector('.js-new-comment-form');

  selectElements = function() {
    _this.actions = commentForm.querySelector('.form-actions');
    _this.bubblesContent = document.querySelectorAll('.discussion-bubble.js-comment-container');
    _this.bubble = _this.bubblesContent[_this.bubblesContent.length - 1];
    _this.close = _this.actions.querySelector('.js-comment-and-button');
    _this.comment = _this.actions.querySelector('.primary');
    return _this.textarea = commentForm.querySelector('textarea');
  };

  if (commentForm) {
    selectElements();
    MutationObserver = WebKitMutationObserver || MozMutationObserver;
    observer = new MutationObserver(function(mutations) {
      return mutations.forEach(function(mutation) {
        return selectElements();
      });
    });
    observer.observe(this.actions, {
      childList: true
    });
    button = function(text, innerHtml, closable) {
      var btn;
      if (closable == null) {
        closable = true;
      }
      btn = document.createElement('button');
      btn.innerHTML = text;
      btn.className = 'button';
      btn.setAttribute('tabindex', '1');
      btn.setAttribute('type', 'submit');
      btn.setAttribute('title', innerHtml);
      btn.setAttribute('style', 'margin-right: 4px;');
      btn.addEventListener('click', function(event) {
        event.preventDefault();
        _this.textarea.value += " " + innerHtml;
        if (closable) {
          _this.close.click();
        } else {
          _this.comment.click();
        }
        return _this.textarea.value = '';
      });
      return btn;
    };
    insertButtons = function() {
      var btn, div;
      div = document.createElement('div');
      div.setAttribute('style', 'float: left; margin: -40px 0px 0px 60px;');
      btn = button('Sample app', 'Can you please provide a sample application that reproduces the error?', false);
      div.appendChild(btn);
      btn = button("Wiki", "The wiki is maintained by the community. So if there aren't any up to date instructions, we recommend you to explore the solution yourself and hopefully contribute your findings back!");
      div.appendChild(btn);
      btn = button("ML", "Please use the mailing list or StackOverflow for questions");
      div.appendChild(btn);
      btn = button("Bad bug report", "You need to give us more information on how to reproduce this issue, otherwise there is nothing we can do. Please read CONTRIBUTING.md file for more information about creating bug reports. Thanks!");
      div.appendChild(btn);
      btn = button("<img src='https://a248.e.akamai.net/assets.github.com/images/icons/emoji/shipit.png' width='14' height='14'>", ":shipit:", false);
      div.appendChild(btn);
      btn = button("<img src='https://a248.e.akamai.net/assets.github.com/images/icons/emoji/heart.png' width='14' height='14'>", ":heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:", false);
      div.appendChild(btn);
      return _this.bubble.appendChild(div);
    };
    if (commentForm && this.close) {
      insertButtons();
    }
  }

}).call(this);
